Repository nuth-vireak/QuizApp, pull requests merged in 2023-09, with the labels that each got.

#1 coding on activity_main and activity_splashrean
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/e2g16/quizapp/Splashscreen.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splashscreen.xml
Labels: enhancement

#2 create test
  app/src/main/java/com/e2g16/quizapp/test.java
Labels: help wanted

#3 finish activity_splasdcreen and activity_main
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/e2g16/quizapp/Splashscreen.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splashscreen.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#4 refector code from pok hengly
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/e2g16/quizapp/Fragment/HistoryFragment.kt
  app/src/main/java/com/e2g16/quizapp/Fragment/HomeFragment.kt
  app/src/main/java/com/e2g16/quizapp/Fragment/ProfileFragment.kt
  app/src/main/java/com/e2g16/quizapp/Fragment/SpinFragment.kt
  app/src/main/java/com/e2g16/quizapp/HomeActivity.kt
  app/src/main/res/color/iconscolor.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_spin.xml
  app/src/main/res/menu/menu.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#5 fixed crash
  app/build.gradle.kts
  app/src/main/java/com/e2g16/quizapp/HomeActivity.kt
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/menu/menu.xml
Labels: bug

#6 fixed bug
  app/src/main/java/com/e2g16/quizapp/HomeActivity.kt
Labels: bug

#7 fragment home
  app/src/main/res/layout/fragment_home.xml
Labels: enhancement

#8 add new
  app/build.gradle.kts
  app/src/main/java/com/e2g16/quizapp/Fragment/HomeFragment.kt
  app/src/main/java/com/e2g16/quizapp/adaptor/categoryadaptor.kt
  app/src/main/java/com/e2g16/quizapp/modle/categoryModelClass.kt
  app/src/main/res/layout/categoryitem.xml
  app/src/main/res/layout/fragment_home.xml
Labels: enhancement

#9 fixed bug
  app/src/main/java/com/e2g16/quizapp/Fragment/HomeFragment.kt
  app/src/main/java/com/e2g16/quizapp/adaptor/categoryadaptor.kt
Labels: bug

#16 fixed bugs
  app/src/main/java/com/e2g16/quizapp/Fragment/HistoryFragment.kt
  app/src/main/java/com/e2g16/quizapp/model/HistoryModelClass.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splashscreen.xml
  app/src/main/res/layout/categoryitem.xml
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_spin.xml
  app/src/main/res/layout/historyitem.xml
  app/src/main/res/values/strings.xml
Labels: bug

#17 add new file
  .idea/misc.xml
Labels: duplicate
