Repository nuth-vireak/QuizApp, pull requests merged in 2023-10, with the labels that each got.

#18 Finished on fragment_profile.xml and ProfileFragment.kt
  .idea/misc.xml
  app/src/main/java/com/e2g16/quizapp/Fragment/ProfileFragment.kt
  app/src/main/res/layout/fragment_profile.xml
Labels: enhancement

#19 fix bugs. finished Withdrawal activity and fragment. add Withdrawal view to display in all fragment except fragment_profile.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/e2g16/quizapp/HomeActivity.kt
  app/src/main/java/com/e2g16/quizapp/Splashscreen.kt
  app/src/main/java/com/e2g16/quizapp/Withdrawal.kt
  app/src/main/java/com/e2g16/quizapp/fragment/HistoryFragment.kt
  app/src/main/java/com/e2g16/quizapp/fragment/HomeFragment.kt
  app/src/main/java/com/e2g16/quizapp/fragment/ProfileFragment.kt
  app/src/main/java/com/e2g16/quizapp/fragment/SpinFragment.kt
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_spin.xml
  app/src/main/res/layout/fragment_withdrawal.xml
  app/src/main/res/navigation/navigation.xml
Labels: bug, duplicate, enhancement

#20 Finished QuizActivity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/e2g16/quizapp/QuizActivity.kt
  app/src/main/java/com/e2g16/quizapp/adaptor/CategoryAdaptor.kt
  app/src/main/java/com/e2g16/quizapp/fragment/HomeFragment.kt
  app/src/main/res/layout/activity_quiz.xml
  app/src/main/res/layout/categoryitem.xml
Labels: enhancement

#21 Finished coding on UI
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/e2g16/quizapp/fragment/HomeFragment.kt
  app/src/main/res/color/iconscolor.xml
  app/src/main/res/font/poppins_bold.ttf
  app/src/main/res/font/poppins_extrabold.ttf
  app/src/main/res/font/poppins_light.ttf
  app/src/main/res/font/poppins_regular.ttf
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_quiz.xml
  app/src/main/res/layout/activity_splashscreen.xml
  app/src/main/res/layout/categoryitem.xml
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_spin.xml
  app/src/main/res/layout/fragment_withdrawal.xml
  app/src/main/res/layout/historyitem.xml
Labels: enhancement

#25 Add Firebase User Registration and Login in MainActivity
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/e2g16/quizapp/MainActivity.kt
  app/src/main/java/com/e2g16/quizapp/fragment/SpinFragment.kt
  app/src/main/java/com/e2g16/quizapp/model/User.kt
  app/src/main/res/layout/activity_main.xml
  build.gradle.kts
Labels: enhancement

#28 Implemented Data Binding with ValueEventListener in Four Fragments
  app/google-services.json
  app/src/main/java/com/e2g16/quizapp/fragment/HistoryFragment.kt
  app/src/main/java/com/e2g16/quizapp/fragment/HomeFragment.kt
  app/src/main/java/com/e2g16/quizapp/fragment/ProfileFragment.kt
  app/src/main/java/com/e2g16/quizapp/fragment/SpinFragment.kt
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_spin.xml
Labels: enhancement

#29 Implemented Quiz Activity Functionality
  app/build.gradle.kts
  app/src/main/java/com/e2g16/quizapp/QuizActivity.kt
  app/src/main/java/com/e2g16/quizapp/adaptor/CategoryAdaptor.kt
  app/src/main/java/com/e2g16/quizapp/fragment/HomeFragment.kt
  app/src/main/java/com/e2g16/quizapp/model/Question.kt
  app/src/main/res/layout/activity_quiz.xml
Labels: enhancement

#31 working on quiz activity
  app/src/main/java/com/e2g16/quizapp/QuizActivity.kt
  app/src/main/java/com/e2g16/quizapp/adaptor/CategoryAdaptor.kt
  app/src/main/java/com/e2g16/quizapp/fragment/HomeFragment.kt
  app/src/main/res/layout/activity_quiz.xml
  app/src/main/res/layout/categoryitem.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#32 get 1 point of play chance after successful after become a winner
  app/src/main/java/com/e2g16/quizapp/QuizActivity.kt
Labels: enhancement

#33 finish andriod
  app/src/main/java/com/e2g16/quizapp/QuizActivity.kt
  app/src/main/java/com/e2g16/quizapp/Withdrawal.kt
  app/src/main/java/com/e2g16/quizapp/adaptor/HistoryAdaptor.kt
  app/src/main/java/com/e2g16/quizapp/fragment/HistoryFragment.kt
  app/src/main/java/com/e2g16/quizapp/fragment/HomeFragment.kt
  app/src/main/java/com/e2g16/quizapp/fragment/SpinFragment.kt
  app/src/main/java/com/e2g16/quizapp/model/HistoryModelClass.kt
  app/src/main/res/layout/activity_quiz.xml
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_spin.xml
  app/src/main/res/layout/fragment_withdrawal.xml
Labels: bug, enhancement, help wanted
